const productTypes = {
  // all
  SET_PRODUCTS_LOADING: "SET_PRODUCTS_LOADING",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCTS_ERROR: "SET_PRODUCTS_ERROR",

  // actions
  SET_ACTION_PRODUCT_LOADING: "SET_ACTION_PRODUCT_LOADING",
  SET_ACTION_PRODUCT: "SET_ACTION_PRODUCT",
  SET_ACTION_PRODUCT_ERROR: "SET_ACTION_PRODUCT_ERROR",

  // single
  SET_PRODUCT_LOADING: "SET_PRODUCT_LOADING",
  SET_PRODUCT: "SET_PRODUCT",
  SET_PRODUCT_ERROR: "SET_PRODUCT_ERROR",
};

export default productTypes;
